### ISSUE TITLE
Omega Reset

### ISSUE THREAD

**Issue by keilmillerjr** [thoughtbot/neat#107]
http://joshfry.me/notes/omega-reset-for-bourbon-neat/
https://github.com/joshfry/omega-reset-for-bourbon-neat

``` sass
$small-screen: new-breakpoint(min-width 320px max-width 480px 4)

ul
  +span-columns(12)
  li
    +span-columns(2 of 12)
    +omega(6n)
    +media($small-screen)
      +span-columns(1 of 4)
      +omega(4n)
```

The following should yield a result when browser is small, a new row after the 4th list item, and then the 6th list item, and so on.

Omega reset fixes this.

``` scss
@mixin omega-reset($nth) {
  &:nth-child(#{$nth}) { margin-right: flex-gutter(); }
  &:nth-child(#{$nth}+1) { clear: none }
}
```

However, I can't get the margin to work. flex-gutter() isn't working for me, even when declaring the following:

``` sass
$fg-column: $column
$fg-gutter: $gutter
$fg-max-columns: 12
```

Any ideas?
