### ISSUE TITLE
Fixed width for outer-container

### ISSUE THREAD

**Issue by riqswe** [thoughtbot/neat#129]
Hey @kaishin!

I'm using Neat for a CMS where I don't need the "responsiveness". It may sound silly but I was wondering if worth add to `outer-container` something like?

``` scss
@mixin outer-container($fluid: fluid) {
  @include clearfix;
  max-width: $max-width;

  @if $fluid == fixed {
    min-width: $max-width;
  }

  margin: {
    left: auto;
    right: auto;
  }
}
```

What do you think?
