### ISSUE TITLE
Media breakpoint variable not working correctly

### ISSUE THREAD

**Issue by kilmc** [thoughtbot/neat#141]
I searched through the docs and people's examples and couldn't find anyone talking about this problem so it's probably me being dumb.

I have at the top of my scss file.

``` SCSS
@import 'helpers';
@import 'vendor/bourbon/bourbon';
@import 'vendor/neat/neat';
@import 'reset';
```

Inside helpers I'm setting the breakpoint as `$mobile: new-breakpoint(max-width 480px 4);` but the output from the include is just rendering the variables' content and not the correct media query syntax

``` SCSS
// scss
h2 {
  font-size: 3rem;
  @include media($mobile) {
    font-size: 2rem;
  }
}

// css 
@media screen and (min-width: new-breakpoint(max-width 480px 4)) {
  h2 {
    font-size: 2rem;
  }
}

Any help would be appreciated.
Thanks
```
