### ISSUE TITLE
omega() mixin incorrectly converts queries like "3n+2"

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/neat#145]
Given this SCSS:

``` scss
.category {
  @include span-columns(4);
  @include omega(3n+2, block);
}
```

I expect to have Neat generate `&:nth-child(3n+2)` with a margin of 0, and `&:nth-child(3n+3)` with `clear: left`. Instead, I get this:

``` css
.category:last-child {
  margin-right: 0; }
  .category:nth-child(5n) {
    margin-block: 0; }
  .category:nth-child(5n+1) {
    clear: left; }
```

I believe SCSS is converting `3n+2` to `5n` (3+2=5).
