### ISSUE TITLE
Is re-ordering columns possible?

### ISSUE THREAD

**Issue by donaldallen** [thoughtbot/neat#229]
I've tried something like this:

``` scss
main {
  @include outer-container;
}

article {
  @include span-columns(10);
  @include shift(2);
  background-color:red;
}

aside {
  @include span-columns(2);
  @include shift(-8);
  background-color:blue;
}
```

But it doesn't work. How does everyone else do it?
