### ISSUE TITLE
Use is-even function

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/neat#238]
[This](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/functions/_new-breakpoint.scss#L37) should use [is-even](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/functions/_private.scss#L2) function rather than do the check manually.

``` scss
@else if length($query) % 2 == 0 {
  $query: append($query, $total-columns);
}
```

... should be:

``` scss
@else if is-even(length($query)) {
  $query: append($query, $total-columns);
}
```

Same [here](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_media.scss#L72).

``` scss
@if length($query) % 2 != 0 { ... }
```

... should be:

``` scss
@if not is-even(length($query)) { ... }
```

You could even build an `is-odd` function.

``` scss
@function is-odd($int) {
  @return not is-even($int);
}
```
