### ISSUE TITLE
Slightly more elegant is-display-table function

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/neat#241]
https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_private.scss#L33-L43

``` scss
@function is-display-table($container-is-display-table, $display) {
  $display-table: false;

  @if $container-is-display-table == true {
    $display-table: true;
  } @else if $display == table {
    $display-table: true;
  }

  @return $display-table;
}
```

... should be:

``` scss
@function is-display-table($container-is-display-table, $display) {
  @return $container-is-display-table or $display == table;
}
```
