### ISSUE TITLE
omega nth-child breaks when no `n` is provided

### ISSUE THREAD

**Issue by jo-asakura** [thoughtbot/neat#251]
`nth-child` mixin in /grid/_omega.scss throws an error: `Error: Invalid CSS after "&:nth-child(2": expected ")", was "+1)"` in case you provide a number with no `n`. There should be a verifications step for `$query` to catch all the cases when there is no `n` provided.

There a fix for it:
```css
@mixin nth-child($query, $direction) {
  $opposite-direction: get-opposite-direction($direction);

  &:nth-child(#{$query}) {
    margin-#{$direction}: 0;
  }

  @if type-of($query) == number {
    $idx: str-index($query + '', 'n');
    @if ($idx and $idx >= 1) {
      &:nth-child(#{$query}+1) {
        clear: $opposite-direction;
      }
    }
  }
}
```
