### ISSUE TITLE
What about 100% grid

### ISSUE THREAD

**Issue by shivapoudel** [thoughtbot/neat#263]
In bourbon there's a `flex-grid` but that utilizes 

``` scss
$fg-column: 60px;             // Column Width
$fg-gutter: 25px;             // Gutter Width
$fg-max-columns: 12;          // Total Columns For Main Container
```

Rather that this in my theme I want the footer section be 100% adapt to the windows size. So how can I implement this math with neat and bourbon.

``` scss
$flex-gutter: 6%;

@function axis-flex-grid( $columns: 1, $container-columns: 1 ) {
    $width: ( ( ( 100% - ( $flex-gutter * ( $container-columns - 1 ) ) ) / $container-columns ) * $columns ) + ( $flex-gutter * ( $columns - 1 ) );
    @return $width;
}
```

Remember folks:

Whenever I use:

``` scss
div .axis_one_half {
    margin-left: 6%;
    width: flex-grid(1, 5);
}
div .axis_one_half {
    margin-left: 6%;
    width: axis-flex-grid(1, 5);
}
```

I got different css output result:

``` css
.axis_one_half {
  width: 41.37931%; // Confused in this calc :o
}

.axis_one_half {
  width: 47%; // Since the gutter is 6% :)
}
```

Sort this issues in neat Guys :)
