### ISSUE TITLE
Media query conversion bug when compiling scss to css

### ISSUE THREAD

**Issue by Anima-t3d** [thoughtbot/neat#273]
**I'm using neat 1.7 and updated from 1.5**. Previously I used built in neat from prepros (4.1 at that time). However a few months later I have to update the project and in the meanwhile prepros changed to 5.x and the built in neat no longer worked. I then installed neat using gem install and have 1.7 successfully installed (I can see the folders). **So the bug described below may or may not be due to neat and/or prepros**, I would like if someone could clear it up so I can file the bug accordingly (either here or prepros). Perhaps this is caused by https://github.com/thoughtbot/neat/commit/a9da0cf96816dfe470a926c8b296d93c3375cb27?

When having code like this in **scss**:
```scss
@include media(max-width em(1620))
{
	padding: 25px;
}
```
Outputs in **css** to this (notice extra and, which leads to website not being responsive):
```css
@media screen and (max-width: 101.25em) and  {
    .message {
      padding: 25px; } }
```
When having code like this in **scss** (**using breakpoint definitions**):
```scss
@include media($t800)
{
	border-width: 6px;
}
```
Outputs in **css** to this (notice no extra and):
```css
@media screen and (max-width: 801px)  {
      #wrapper #frame {
        border-width: 6px; } }
```
