### ISSUE TITLE
How to get column width?

### ISSUE THREAD

**Issue by beckyconning** [thoughtbot/neat#281]
`$column` works on desktop but on mobile `$column` seems almost unrelated to the width of the column. is there a way to get consistent column width as a variable or similar?

**Comment by kaishin** [comment]
Column width is a percentage that depends on the value of the gutter and the number of columns. There is no way to get its absolute width without doing the math yourself.

**Comment by beckyconning** [comment]
I think its totally reasonable to call this out of scope and close the issue but do you know what that calculation would look like?

**Comment by kaishin** [comment]
This is what the implementation looks like. As you can see it's all percentage based.

```scss
width: flex-grid($columns, $container-columns) + flex-gutter($container-columns);

@function flex-grid($columns, $container-columns: $fg-max-columns) {
  $width: $columns * $column + ($columns - 1) * $gutter;
  $container-width: $container-columns * $fg-column + ($container-columns - 1) * $gutter;
  @return percentage($width / $container-width);
}

@function flex-gutter($container-columns: $fg-max-columns, $gutter: $gutter) {
  $container-width: $container-columns * $column + ($container-columns - 1) * $gutter;
  @return percentage($gutter / $container-width);
}
```

The default values of `$gutter` and `$column` are:

```scss
$column: golden-ratio(1em, 3) !default;
$gutter: golden-ratio(1em, 1) !default;
```
