### ISSUE TITLE
Chrome Visual-Grid Alignment Issues

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/neat#307]
I'm trying to align elements properly using the visual-grid feature of bourbon and am having pixel-perfect alignment issues. I believe it has to do with the decimal place strategy, but I've never seen this in a grid framework, and wouldn't think this is ideal.

```scss
$visual-grid: true;
$max-width: em(1200) !global; //this just changes the alignment issues, removing it does not fix it.

header.header {
  .container {
    @include outer-container();
    .logo {
      @include span-columns(2);
      background-color: red;
    }
    .action {
      @include span-columns(2);
      background-color: green;
    }
    .navigation {
      @include span-columns(7);
      background-color: orange;
    }
    .user {
      @include span-columns(1);
      @include omega();
      background-color: blue;
    }
  }
}
```

```haml
%header.header
  .container
    .logo
      logo
    .action
      action
    .navigation
      nav
    .user
      user
```

Output:
![screen shot 2015-02-03 at 8 48 20 pm](https://cloud.githubusercontent.com/assets/1342064/6033619/0920379a-abe6-11e4-9d99-11933ffae942.png)

While it's quite difficult to see, the width of the red "logo" element is too small compared to the visual-grid helpers, leading to the rest of the elements being off.

It looks like the visual-grid is drawn using webkit and moz mixins doing gradients. While this strategy makes sense at large, I've had very little reliability with em sizes, extreme precision, percentages, and the chrome browser at large.

Any ideas for a fix? Has this been noticed by anyone else?
