### ISSUE TITLE
Showing the visual grid only when a bodyclass is here.

### ISSUE THREAD

**Issue by labo-css** [thoughtbot/neat#335]
After a lot of time, wondering why my visual grid weren't working i finally got it responsive, but... i want to activate/desactivate it via jade (or html) by putting a class in the body when in dev.

So when i have body class="indev" the grid show, and if indev is not present, the layout is visual grid free.

How i can manage to do this?
Thanx.

**Comment by jklegseth** [comment]
The ideal way to do this is to set the `$visual-grid` boolean so that when `false` you don't just hide the grid, you don't load it at all. You can't set Sass variables based on a DOM element's class attribute (nor should you really want to). 

It can be done using a class like you suggest but it's a poor hack that uses cascading and selector specificity. For example, add the class `nogrid` when you don't want to show the grid, and then:

```scss
.nogrid:before {
    background-image: none;
}
```

But please don't do that, as it leaves all the grid CSS in your stylesheet, adding cruft and file size when turned off.

This is perfect use case for some kind of environment setting, which will just take care of it for you. For example, if you're using Compass you can check out `compass-env()` ([http://compass-style.org/reference/compass/helpers/env/#compass-env](http://compass-style.org/reference/compass/helpers/env/#compass-env)). Something like this would do the trick:

```scss
// Default setting is off
$visual-grid: false;

// Turn the grid on if we're in development
@if compass-env() == 'development' {
    $visual-grid: true;
}
```

You can read more about Compass enviornments at [http://compass-style.org/help/tutorials/production-css/](http://compass-style.org/help/tutorials/production-css/).
