### ISSUE TITLE
Matching visual grid width to outer-container max-width

### ISSUE THREAD

**Issue by omerbalyali** [thoughtbot/neat#353]
Hi,

Are there any way to match the visual grid width to outer-container max-width, rather than a global max-width?

The problem is that I choose other than a 100% width for outer-container in different breakpoints, but visual-grid aligns itself to 100% width and it does not make sense. I searched on web, read source code and docs but couldn't find an answer.

Also there is a variable $visual-grid-breakpoints, but I couldn't figured it out how to use it...

Thanks,

**Comment by jklegseth** [comment]
I don't think it's possible unless you want to do some hacking. I'm sure you've seen the logic for the grid ([https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_visual-grid.scss](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_visual-grid.scss)) -- `grid-columns`, `$max-width` are used from the default settings (or your overrides) and `width: 100%` is set. And since the grids are styled using `position: fixed` on the `body:after` pseudo element they aren't affected even if you try `body { width: 75%; }`.

You might be able to leverage that partial to make your own mixin for debugging purposes. For example I just threw this together as a proof of concept. I'm sure it is frail but t seems like the right general idea. 
 
```scss
// $width should match parent width
// $stops are number of grids you want
@mixin add-grid($width, $stops) {
  // Need this on parent element to use absolute positioning below
  position: relative;

  &:before {
    @include grid-column-gradient(gradient-stops($stops));
    content: "";
    display: inline-block;
    height: 100%;
    left: 0;
    max-width: $width;
    opacity: .3;
    pointer-events: none;
    position: absolute;
    right: 0;
    width: $width;
  }
}

.my-container {
  @include add-grid(560px, 12);
  width: 560px;
}
```

And then some HTML:

```html
<div class="my-container">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores voluptatum officia repudiandae placeat necessitatibus cupiditate, itaque explicabo unde deserunt vero maxime tempora commodi nostrum laboriosam facere impedit inventore quam, beatae iure. Tempore voluptates ut architecto ipsa, sed pariatur provident non tenetur labore, laboriosam numquam eaque soluta totam, quis nisi doloribus rem quasi impedit.
</div>
```

I'd put it up on a fiddle for you but I don't know of a way to use Bourbon and Neat as linked external resources.
