### ISSUE TITLE
Getting 6 columns when I think I should be getting 8

### ISSUE THREAD

**Issue by blokezero** [thoughtbot/neat#357]
I've got a responsive design with different columns based on 8 for desktop going down to 6 for tablet using Neat, this is the relevant bit:

```scss
$tablet-max: 1024px;
$tablet-min: 500px;
$small-mobile-min: 320px;

$tablet-viewport: new-breakpoint(min-width $tablet-min max-width $tablet-max 6);
$desktop-up: new-breakpoint(min-width $tablet-max + 1);
```

Everything is working well except for when I add this query to my main content block which I want to to be 4 of 6 cols for tablet and 4 of 8 for desktop (it's mobile first, 8 cols):

```scss
main, div.main-article {
  @include span-columns(8);
  @include omega;
  @include media($tablet-viewport) {
    @include span-columns(4 of 6);
  }

  @debug $tablet-max;
  @include media ($desktop-up) {
    padding-left: $gutter;
    @include shift(2);
    @include span-columns(4);
  }
}
```

Works great for the tablet view but just including the `$tablet-viewport` bit makes the desktop view think there are 6 columns rather than 8 and so all the margin values get messed up.

What am I doing wrong?

Here is a link to a zipped directory with an example, the problematic line is 40 of assets/scss/main.scss

https://www.dropbox.com/s/w5wa6aa94lpvozw/neat_col_test.zip?dl=0

**Comment by jklegseth** [comment]
The first way is to provide the `$container-columns` variable (see [http://thoughtbot.github.io/neat-docs/latest/#span-columns](http://thoughtbot.github.io/neat-docs/latest/#span-columns)) in the `desktop-up` media query:

```scss
@include media ($desktop-up) {
  padding-left: $gutter;
  @include shift(2 of 8);
  @include span-columns(4 of 8);
}
```

You could also write this without needing two media queries by having a default and override with a single media query. You don't need the `$container-columns`  variable I added above because 8 columns is explicit:
```scss
.main, div.main-article {
  @include span-columns(8);
  @include omega;
  @include shift(2);
  @include span-columns(4);
  padding-left: $gutter;

  @include media($tablet-viewport) {
    @include shift(0);
    @include span-columns(4 of 6);
  }
}
```

If you have the default number of columns set to 8, you can lose the `span-columns` line in the above example as well:

```scss
.main, div.main-article {
  @include omega;
  @include shift(2);
  @include span-columns(4);
  padding-left: $gutter;

  @include media($tablet-viewport) {
    @include shift(0);
    @include span-columns(4 of 6);
  }
}
```
