### ISSUE TITLE
shifting not working for me

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/neat#378]
Hello

I got the following code:

```html
<div class="container">
    <div class="content child child--one">main</div>
    <div class="aside-primary child child--two">primary</div>
    <div class="aside-secondary child child--three">secondary</div>
</div>
```

I'd like to show the columns like: secondary - content - primary

this is the css:

```scss
.container {
  @include outer-container(800px);
}

.child {
  background-color: rgba(#000, 0.25);
  height: 200px;
}

.child--one {
  @include pad;
  @include span-columns(7);
  @include shift(2);
  
}

.child-two {
  @include span-columns(3);
  @include shift(9)

}

.child-three {
  @include span-columns(2);
  @include shift(-12);
}
```

what am I missing?

http://codepen.io/anon/pen/WvVPvp?editors=110

thank you in advance for your input
