### ISSUE TITLE
Any plans for Bidi support

### ISSUE THREAD

**Issue by ahwebd** [thoughtbot/neat#386]
Thanks for this great grid system,

Currently neat supports either LTR or RTL, but not both at the same time (Bidi).

I ended up now creating own mixins on top of neat to get this.

Examples:
```css
// Compile rtl css if set to true
$rtl: true;

@mixin ara-rtl() {
  @if $rtl {
    [dir="rtl"] & {
      @include direction-context(right-to-left) {
        @content;
      }
    }
  }
}

@mixin ara-shift ($shift) {
  @include shift($shift);
  @include ara-rtl {
    margin-left: 0;
    @include shift($shift);
  }
}

@mixin ara-span-columns($span) {
  @include span-columns($span, block-collapse);
  @include ara-rtl {
    float: right;
  }
}
```

Bidirectional support involves not only generating css for RTL, but also resetting LTR specific css.

Getting neat to support bidi out of the box will be a great feature.
