### ISSUE TITLE
@import "neat" adds rules to resulting css file.

### ISSUE THREAD

**Issue by kilianc** [thoughtbot/neat#399]
```css
html{box-sizing:border-box}
*,:after,:before{box-sizing:inherit}
```

Every time I import neat I end up with this at the top, which is unfortunate if you work with webpack or simply have multiple css files and "core" file.

There should at least be a way to turn it off. IMHO they should be two different import or the "reset" should be a mixin. This is the equivalent of a library writing to stdout :)
