### ISSUE TITLE
right to left layout

### ISSUE THREAD

**Issue by dustinsmith1024** [thoughtbot/neat#40]
I was trying to do a right hand nav and noticed there wasn't an easy way to make content higher up in the document be positioned to the right.

I ended up just doing this on the last element for now.

``` css
float: right;
margin-right: none;
```

I worked up some code locally to allow a new display 'right-to-left' layout.

``` scss
  @else if $display == right-to-left {
    display: block;
    float: right;
    margin-left: flex-gutter($container-columns);
    margin-right: auto;
    width: flex-grid($columns, $container-columns);

    &:last-child {
      margin-left: 0;
      margin-right: auto;
    }
  }

  @else {
    display: block;
    float: left;
    margin-left: auto;
    margin-right: flex-gutter($container-columns);
    width: flex-grid($columns, $container-columns);

    &:last-child {
      margin-right: 0;
      margin-left: auto;
    }
  }
```

``` scss
.container {
  @include outer-container;
  aside {
    @include span-columns(2, 'right-to-left');
  }
  article {
    @include span-columns(10, 'right-to-left');
  }
}
```

This has the same issues as the table layout issue, where you have to put right to left on each.  

Let me know what you think, or if theres a better way to accomplish it.  I can submit a pull request if you think its needed.
