### ISSUE TITLE
nth-omega requires $nth argument as a string

### ISSUE THREAD

**Issue by underscorebrody** [thoughtbot/neat#42]
Due to the way SASS evaluates expressions, any complex argument to the nth-omega mixin will not give the expected result unless the argument is passed as a string.

Problematic example:

``` scss
li { @include nth-omega(3n+5);} 
```

Result:

``` css
li:nth-omega(8n) { margin-right:0; }
```

Whereas this one evaluates as expected:

``` scss
li { @include nth-omega("3n+5"); }
```

Result: 

``` css
li:nth-omega(3n+5) { margin-right:0; }
```

I've tried out a few things and I'm not sure that there is a good solution to this other than making it clear in the documentation, as the argument has already been evaluated by the time it gets to the mixin.
