### ISSUE TITLE
block-collapse with omega and shift ruins columns

### ISSUE THREAD

**Issue by ogonkov** [thoughtbot/neat#423]
Is it possible to use `block-collapse` with `omega` and `shift-in-context`?
The next example makes all second items (with orange background) to skip to new row. Seems like some error with shift/column/gutter computation?

![neat_strange_computation](https://cloud.githubusercontent.com/assets/1091927/13432529/1553d386-dfdf-11e5-96b0-48290ab3c465.png)

```scss
$em-base: 17px;
@import "bourbon/bourbon";
$border-box-sizing: false;
$column: em(40); // 2.5em
$gutter: em(20); // 1.25em
$grid-columns: 16;
$max-width: em(940); // 58.75em
$visual-grid: true;
$visual-grid-index: front;
$visual-grid-color: #ed0b6d;
@import "neat/neat";
html, body {
  font-size: $em-base;
}

.outer {
  @include outer-container;
}

.main {
  @include span-columns(11);
}

.list {
  background-color: green;
  padding: 0;
  list-style: none;
  @include outer-container;
  
  &__item {
    background-color: red;
    @include span-columns(5 of 11, block-collapse);
    @include omega(2n);
    
    &:nth-child(2n + 2) {
      background-color: orange;
      @include shift-in-context(1 of 16);
    }
  }
}
```
```html
<div class="outer">
  <div class="main">
    <div class="list">
      <div class="list__item">Item 1</div>
      <div class="list__item">Item 2</div>
      <div class="list__item">Item 3</div>
      <div class="list__item">Item 4</div>
      <div class="list__item">Item 5</div>
    </div>
  </div>
</div>
```
P. S. Also last column gets wrong width.
