### ISSUE TITLE
Remove hard coded "screen" media type from @media mixin?

### ISSUE THREAD

**Issue by ThomasFett** [thoughtbot/neat#435]
I came across this issue when creating a print CSS. Since the @media mixin starts all media queries with a hard coded `"screen and "` I either needed to overwrite the mixin by myself or to duplicate the respective styles.
Is there any reason to restrict the mixin only to the media type screen? Otherwise I would suggest to make it configurable or at least replace the hard coded part with `"all and "`.

The related LOC can be found here:
https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_media.scss#L67

**Comment by whmii** [comment]
They should be able to inherit the global grid styles. I would handwrite a regular mediaquery and go from there.

Alternatively I would place the something like following in your mixin lib and go from there:

```scss

@mixin media-2($query: $feature $value $columns, $total-columns: $grid-columns) {
  @if length($query) == 1 {
    @media ($default-feature: nth($query, 1)) {
      $default-grid-columns: $grid-columns;
      $grid-columns: $total-columns !global;
      @content;
      $grid-columns: $default-grid-columns !global;
    }
  } @else {
    $loop-to: length($query);
    $media-query: "screen and ";
    $default-grid-columns: $grid-columns;
    $grid-columns: $total-columns !global;

    @if is-not(is-even(length($query))) {
      $grid-columns: nth($query, $loop-to) !global;
      $loop-to: $loop-to - 1;
    }

    $i: 1;
    @while $i <= $loop-to {
      $media-query: $media-query + "(" + nth($query, $i) + ": " + nth($query, $i + 1) + ") ";

      @if ($i + 1) != $loop-to {
        $media-query: $media-query + "and ";
      }

      $i: $i + 2;
    }

    @media #{$media-query} {
      @content;
      $grid-columns: $default-grid-columns !global;
    }
  }
}
```
