### ISSUE TITLE
Consider progressive enhancement calc() for column width

### ISSUE THREAD

**Issue by jsit** [thoughtbot/neat#438]
As described in this article:

https://www.sitepoint.com/a-tale-of-css-and-sass-precision/

Would be something like this in [`_span-columns.scss`](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_span-columns.scss):

```scss
@if $display-table  {
  display: table-cell;
  width: percentage($columns / $container-columns);
  width: calc(#{$columns} / #{$container-columns});
```

Browser that support `calc` would use the second value, browsers that don't would continue to use approximate percentages.
