### ISSUE TITLE
Add warning when gutter is defined in ems

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#473]
Because of the way things are calculated, it could be vary dangerous to define gutters in `em`s.

I'm thinking of adding a warning.

**Comment by tysongach** [comment]
- What are the implications of doing so?
- Do these implications make Neat or the grid system less functional in some way?
- Is it worth adding code complexity for this? Or would a recommendation in the docs suffice?
- A hunch tells me that this is black or white, and that there is probably some instance where an em-based gutter could be valuable. It’d be awfully annoying if the grid system yelled at you for doing that.

**Comment by whmii** [comment]
kk

**Comment by tysongach** [comment]
@whmii These are questions. Meant to spark discussions and talk about what’s best and why. Plus, having these conversations on GitHub are great for looking back on later…

**Comment by whmii** [comment]
To clarify, the primary concern/motivation is around something like the following.

```scss
.col-1 {
  @include grid-col(6);
  font-size: 20px;
}

.col-2 {
  @include grid-col(6);
  font-size: 200px;
}
```

If the gutter were to be defined in `em`s, the layout would likely break. IMO I think your comment toward just putting something in the docs about it would be satisfactory. The issue only comes in to play with 2 siblings of different sizes. You could totally do gutters in ems it as long as you did something like:


```scss
.container-1 {
  @include grid-container;
  font-size: 20px;
}

.container-2 {
  @include grid-container;
  font-size: 200px;
}

.container__col {
  @include grid-col(6);
}

```
