### ISSUE TITLE
Is Neat 2.0 working as expected?

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/neat#477]
We put the pre-release on the new Bourbon site and I just noticed that grid columns have all `margin-left` applied and no `margin-right`. Is this expected?

I was under the assumption that a grid column would have equal gutter on either side, which is to say it should have a `margin-left` _and_ `margin-right`. If the grid has `1rem` gutters, a column would have `0.5rem` margins on the left and right.

The output of a column that I’m seeing is:

```css
.column {
  width: calc(25% - 2.5rem);
  float: left;
  margin-left: 2rem;
}
```

cc: @whmii
