### ISSUE TITLE
Static Columns

### ISSUE THREAD

**Issue by Belpois** [thoughtbot/neat#554]
Is there a way to have a static column?

Imagine you have **3 columns**, **(A | B | C)**, A is set to 100px and never changes, whereas **B** and **C** will grow and shrink accordingly.

Thanks

**Comment by whmii** [comment]
no there is not.

For this you would want to either use flexbox or something like…

``` css
.a {
  width: 100px;
}

.b,
.c {
  width: calc((100% - 100px) / 2);
}
```
