### ISSUE TITLE
Media Queries and Grid Media

### ISSUE THREAD

**Issue by christiantype** [thoughtbot/neat#622]
I'm working on a website that requires responsive media queries. 

I have my desktop grid here:

```scss
$desktop-grid: (
  columns: 12,
  gutter: 50px,
  media: 1366px,
);
```

and 

```scss
$mobile-grid: (
  columns: 12,
  gutter: 20px,
  media: 400px,
);
```

Is the `media` referring to max-width or min-width?

What would be the best way to include multiple queries in the element below?

```scss
.post-card {
  @include grid-column(6);
  margin-bottom: 3em;
  position: relative;
  list-style: none;
}
```

I would love to have `.post-card` be 12 columns under 400px and be able to add additional css styling.

**Comment by kgcreative** [comment]
Hi @christiantype,

Per [the docs](http://neat.bourbon.io/docs/latest/#custom-grids), media is either a number(with unit) - such as 1200px, or 12em (in which case, it's min-width), or a string for more complex queries.

In your case, the correct syntax for your mobile grid would be:
```
$mobile-grid: (
        columns: 12,
        gutter: 20px,
        media: 'only screen and (max-width: 399px)',
);
 ```

and then for the .post card itself:

```
.post-card {
@include grid-column(6);
    margin-bottom: 3em;
    position: relative;
    list-style: none;

    @include grid-media($mobile-grid) {
        @include grid-column(12);
  }
}
```

**Comment by whmii** [comment]
@christiantype To expand on the above, if you are going 'mobile first' (aka your styles default to the small screen and larger screens are styled within mediaqueries using `min-width`, the simplest-ish way to write this would be the following. ⤵

``` scss
$neat-grid: (
  columns: 12,
  gutter: 20px,
);
// this is the default grid anyways so you don't really need this one

mobile: (
  media: 400px,
);

$desktop-grid: (
  gutter: 50px,
  media: 1366px,
);

.post-card {
  @include grid-column(12);
  margin-bottom: 3em;
  position: relative;
  list-style: none;

  @include grid-media($mobile-grid) {
    @include grid-column(6);
    // some more styles
  }

  @include grid-media($desktop-grid) {
    @include grid-column(6);
    // some more styles
  }
}
```
