### ISSUE TITLE
Add $direction argument to row

### ISSUE THREAD

**Issue by paulozoom** [thoughtbot/neat#71]
Currently, it's impossible to have a series of columns with `float: right` and `margin-left`, instead of the opposite. This forces authors to change the order of the HTML elements, which isn't ideal. Adding a `$direction` option to `row`, could fix this problem.

This:

``` scss
ul {
  @include row(block, right);

  > li {
    @include span-columns(6);
  }
}
```

Would generate this code (ommiting non-relevant specifics)

``` css
ul > li {
  float: right;
  margin-left: ...;
}

ul > li:first-child {
  margin-left: 0;
}
```
