### ISSUE TITLE
Add $clear argument to omega

### ISSUE THREAD

**Issue by paulozoom** [thoughtbot/neat#72]
Currently, if one wants to have multiple rows of columns, one has to use both `omega` **and** a different selector with `clear`. Here's an example for a 3-column grid using default settings.

``` scss
.container {
  @include row;

  > * {
    @include span-columns(4);
    @include omega(3n);

    &:nth-child(3n+1) {
      clear: left;
    }
  }
}
```

This could be optimized by doing:

``` scss
.container {
  @include row;

  > * {
    @include span-columns(4);
    @include omega(3n, left, clear);
  }
}
```

Furthermore, when RTL features are added to Neat (see #71), this could take any `$direction` arguments into consideration, ending up with a more clear version: `@include omega(3n, clear);`.
