### ISSUE TITLE
Is it possible to setup or use two different grids on one page?

### ISSUE THREAD

**Issue by Dermotholmes** [thoughtbot/neat#96]
Is it possible to setup or use two different grids on one page? Or Switch off gutters on a row by row basis?

I.e. To declare two different grids with their own gutter and column settings and then use these grids within separate blocks of code on the same page?

The use case I'm looking at is that sometimes I like to use use a grid where different rows of items/elements may or may not want a gutter depending on the the design.

Something along the lines of this attached image.

![eg-01](https://f.cloud.github.com/assets/830488/818832/61096d08-efa1-11e2-8e4e-c0bb4fe69f41.png)

**Comment by toobulkeh** [comment]
:+1: working with designers who live in PSD land, this would be a great feature.

**Comment by ryanburnette** [comment]
Am I missing something, or would it not be possible to just reset `$fg-gutter` temporarily if you wanted to style based on another ratio for a bit?

```sass
$reset-fg-gutter: $fg-gutter
$fg-gutter: [new value]

// do some stuff

$fg-gutter: $reset-fg-gutter
```

Curious to know if it's a viable workaround for now.

+1 to the idea of being able to set custom values on the `outer-container`/`grid-container` mixin.

**Comment by erindotio** [comment]
@kaishin your temporary fix suggestion using `collapse` doesn't work, as it simply extends the width of the column to fill the gap, which leaves the last column in a row (with no gap to begin with), narrower, resulting in columns with uneven widths.

**Comment by jurajhilje** [comment]
+1 to being able to set custom gutter on the ``outer-container`` mixin

**Comment by realpie** [comment]
+1

**Comment by lukerollans** [comment]
+1 would be an amazing feature

**Comment by jaimeeee** [comment]
+1

**Comment by colormono** [comment]
+1

**Comment by tracystone** [comment]
+1

**Comment by kilianc** [comment]
+1

**Comment by acrookston** [comment]
+1

I was able to hack something like this together (it's not pretty but at least proof of concept):

In `neat/grid/_private.scss` replace `flex-grid` and `flex-gutter` to take a column and gutter variable:

```scss
@function flex-grid($columns, $container-columns: $fg-max-columns, $column: $fg-column, $gutter: $fg-gutter) {
  $width: $columns * $column + ($columns - 1) * $gutter;
  $container-width: $container-columns * $column + ($container-columns - 1) * $gutter;
  @return percentage($width / $container-width);
}

@function flex-gutter($container-columns: $fg-max-columns, $column: $fg-column, $gutter: $fg-gutter) {
  $container-width: $container-columns * $column + ($container-columns - 1) * $gutter;
  @return percentage($gutter / $container-width);
}
```

In `neat/grid/_span-column.scss`:
```scss
$fg-column: $column;
$fg-gutter: $gutter;

@mixin span-columns($span: $columns of $container-columns, $column: $fg-column, $gutter: $fg-gutter, $display: block) {
```
Inside that function we pass the `$column` and `$gutter` variables on to `flex-grid` and `flex-gutter`:
```scss
    $flex-grid: flex-grid($columns, $container-columns, $column, $gutter);
    $flex-gutter: flex-gutter($container-columns, $column, $gutter);
```

This gives me the option for each media width (eg mobile or desktop)  to pass `$column` or `$gutter`:

```scss
@include media($medium-screen-only) {
  $column: ($medium-screen - ($grid-columns - 1) * $gutter) / $grid-columns;

    .extras {
      @include span-columns(4, $column);
    }
}
```

This fixed my `$gutter` to always be the same no matter the screen size.

Unfortunately you have to pass variables every time you don't want the default column and gutter size. I'm sure you could modify this to take different `$grid-columns` count (or you might be able to solve that with `span-columns(x of x)`
